# Joe's-MacBook-Air bashrc file

echo "sourced Joes bashrc filee!"

edit() { /usr/local/bin/sublime "$@";}

# options and paths
export PATH="/opt/local/bin:/usr/local/ossh/bin:/usr/local/krb5/bin:$PATH"
export PYTHONPATH="/opt/local/bin/python2.7"
export KRB5_CONFIG=/usr/local/krb5/etc/krb5.conf
export LESSOPEN="| /usr/local/bin/src-hilite-lesspipe.sh %s"
export LESS=' -R '

# Virtual env details
export WORKON_HOME=~/Envs
source virtualenvwrapper.sh-2.7
#workon main

# turn on bash git completion
if [ -f /opt/local/etc/profile.d/bash_completion.sh ]; then
      . /opt/local/etc/profile.d/bash_completion.sh
fi

source /usr/local/etc/bash_completion.d/git-flow-completion.bash