# Common bashrc file

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

export CLICOLOR=1
export LSCOLORS="ExGxFxdxCxDxDxhbadExEx"
export GREP_OPTIONS='--color=auto'
export PS1='\u@\h:\w> '

umask u=rwx,g=rx,o=rx

# Setup PATH Variables
export PATH=$CONF/common/bin:$CONF/plat/$PLAT/bin:$CONF/$SITE/bin:\
$CONF/$SITE/plat/$PLAT/bin:$CONF/$SITE/host/$HOST/bin:\
$CONF/$SITE/host/$HOST/plat/$PLAT/bin:$CONF_LOCAL/common/bin:\
$CONF_LOCAL/plat/$PLAT/bin:$PATH

# Alias
alias ssh='ssh -Y -X'
alias garnet='ssh -X -Y garnet03.erdc.hpc.mil'
alias raptor='ssh -X -Y raptor-l07.afrl.hpc.mil'
alias chugach='ssh -X -Y chugach02.ors.hpc.mil'
alias copper='ssh -X -Y jhamman@copper02.ors.hpc.mil'
alias spirit='ssh -X -Y spirit.afrl.hpc.mil'
alias arctic='ssh -Y arctic.hydro.washington.edu'
alias us='ssh -X -Y us.afrl.hpc.mil'
alias bart='ssh -Y jhamman@bartsimac.hydro.washington.edu'
alias dew='ssh -Y dew.hydro.washington.edu'
alias barttunnel='ssh -N -f -L localhost:7777:localhost:7777 bartsimac.hydro.washington.edu'
alias hydratunnel='ssh -L 7777:localhost:7777 dew.hydro.washington.edu ssh -L 7777:localhost:7777 -N hydra.hydro.washington.edu'
alias pybook_remote='ipython notebook --no-browser --port=7777 --pylab=inline'

export NPSREPO=https://svn.nps.edu/repos/racm
