#! /bin/bash
# Setup a new scope ()

source $CONF_SETUP/setup_functions

make_new_dirs $CONF/plat/$PLAT/                       # platform scope
make_new_dirs $CONF/site/$SITE/                       # site scope
make_new_dirs $CONF/site/$SITE/plat/$PLAT/            # site and platform scope
make_new_dirs $CONF/site/$SITE/host/$HOST/            # host scope
make_new_dirs $CONF/site/$SITE/host/$HOST/plat/$PLAT/ # host and platform scope
make_new_dirs $CONF_LOCAL/plat/$PLAT/                 # platform-specific local installations of software
                                                      # or installed scripts that I didn't write
make_new_dirs $CONF_LOCAL/site/$SITE/                 # site-specific local installations of software
                                                      # or installed scripts that I didn't write
make_new_dirs $CONF_LOCAL/site/$SITE/host/$HOST/      # host-specific local installations of software
                                                      # or installed scripts that I didn't write
make_new_dirs $CONF_LOCAL/site/$SITE/host/$HOST/plat/$PLAT  # host/platform-specific local installations of software
                                                      # or installed scripts that I didn't write

# Add scope to list of scopes
if [ -e $CONF_SETUP/scopes/plat_list ]; then
    if ! grep -q "$PLAT" $CONF_SETUP/scopes/plat_list; then
        echo "Adding current scope to $CONF_SETUP/scopes/plat_list"
        mkdir -p $CONF_SETUP/scopes
        echo $PLAT >> scopes/plat_list
    fi
else
    echo "Adding current scope to $CONF_SETUP/scopes/plat_list"
    mkdir -p $CONF_SETUP/scopes
    echo $PLAT >> scopes/plat_list
fi
if [ -e $CONF_SETUP/scopes/site_list ]; then
    if ! grep -q "$SITE" $CONF_SETUP/scopes/site_list; then
        echo "Adding current scope to $CONF_SETUP/scopes/site_list"
        mkdir -p $CONF_SETUP/scopes
        echo $SITE >> scopes/site_list
    fi
else
    echo "Adding current scope to $CONF_SETUP/scopes/site_list"
    mkdir -p $CONF_SETUP/scopes
    echo $SITE >> scopes/site_list
fi
if [ -e $CONF_SETUP/scopes/host_list ]; then
    if ! grep -q "$HOST" $CONF_SETUP/scopes/host_list; then
        echo "Adding current scope to $CONF_SETUP/scopes/host_list"
        mkdir -p $CONF_SETUP/scopes
        echo $HOST >> scopes/host_list
    fi
else
    echo "Adding current scope to $CONF_SETUP/scopes/host_list"
    mkdir -p $CONF_SETUP/scopes
    echo $HOST >> scopes/host_list
fi