#! /bin/bash
# Setup a portable configuration system
#
# Based on the concepts layed out by Martin Blais
# http://furius.ca/projects/doc/conf.html
#
# Written by Joe Hamman, University of Washington
# Initial Concept  -  2013-10-18

export CONF=$HOME/p/conf
export CONF_SETUP=$PWD
export CONF_LOCAL=$HOME/p/conf-local

export OLD_DOT_FILES=$CONF_SETUP/old_dot_files
mkdir -p $OLD_DOT_FILES

# Make main configuration directories
echo "Making configuration directories"
source $CONF_SETUP/setup_functions

make_new_dirs $CONF/init/                        # global init files,
                                                 # include all the scopes
make_new_dirs $CONF/common/                      # common (shared) scope
make_new_dirs $CONF_LOCAL/common/                # common stuff, install logs, very local

# redirect dot files to look in $CONF/inixt
# The dot files that are currently linked are
# 1.  ~/.profile
# 2.  ~/.bashrc
# 3.  ~/.cshrc
# 4.  ~/.xsession
for file in profile bashrc cshrc xsession; do
    # check if file is already a link
    if [[ -h $HOME/.$file ]]; then
        echo '$HOME/.$file is already a link, moving on...'
    else
        if [[ -e $HOME/.$file ]]; then
            mkdir -p $OLD_DOT_FILES/
            echo "Moving existing $file to $OLD_DOT_FILES/"
            mv $HOME/.$file $OLD_DOT_FILES/$file
        fi
        # make the link
        echo "making $file link: $HOME/.$file --> $CONF/init/$file"
        ln -s $CONF/init/$file $HOME/.$file
    fi
done

# Download $CONF/common/bin files
if [ ! -e $CONF/common/bin/config.guess ]; then
    wget -O $CONF/common/bin/config.guess 'http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD'
    chmod u+x $CONF/common/bin/config.guess
fi

# Get the Current Scope Variables
export PLAT=`$CONF/common/bin/config.guess`

# Get the SITE Variable
if [ -e $HOME/.site ] ; then
    export SITE=`cat $HOME/.site`
else
    if [ -e $CONF_SETUP/scopes/site_list ]; then
        echo 'Existing sites are: '
        cat $CONF_SETUP/scopes/site_list
    fi
    echo "Please Input the current SITE [main]"
    read temp_site
    if [ -z "$temp_site" ] ; then
        SITE='main'
    else
        SITE=$temp_site
    fi
    echo $SITE >> $HOME/.site
fi
echo "Current SITE is set to: $SITE"

# HOST is set to remove the node number from the hostname idenitfier
export HOST='host_not_known'
if [ -e $HOME/.host ] ; then
    export HOST=`cat $HOME/.host`
else
 export HOST=`perl -e'use POSIX qw(uname);$_=(uname)[1];s/\.local$//gi; s/^mg\d.*$/mg/gi;print ($_,"\n")' | cut -f1 -d.`
fi

if [ "$HOST" = "host_not_known" ] ; then
    echo "ERROR:  Unable to determine host name: $HOST"
    echo "You man set the host name in $HOME/.host"
    exit
fi

# Make initial scope configuration directories
echo "Making initial scope directories"
source $CONF_SETUP/new_scope

# Copy generic initialization files
echo "Copying generic initialization files to $CONF/init/"
cp templates/init/* $CONF/init/

# Copy setup directory to $HOME/p/setup
if [ ! -d "$HOME/p/setup/" ]; then
    cp -r $CONF_SETUP $HOME/p/setup/
fi

# Make $HOME/.conf file
if [ ! -e $HOME/.conf ]; then
    echo "Creating $HOME/.conf file"
    cp templates/conf $HOME/.conf
else
    echo '.conf file already exists.  Make sure it contains the environmental variables: CONF, CONF_LOCAL, PLAT, SITE, and HOST'
fi

# Setup Configuration git repository
if [ ! -d "$HOME/p/.git" ]; then
    echo "Initializing git repository"
    cd $HOME/p/
    git init
    git add --all
    git commit -m 'initial commit of config repository'
fi

# Run through a list of other dot files
for file in gitconfig emacs emacs.d vimrc gitignore_global ncviewrc; do
    if [ -e $HOME/.$file ]; then
       echo "copying $HOME/.gitconfig to $OLD_DOT_FILES/$file"
       cp $HOME/.gitconfig $OLD_DOT_FILES/$file
       if [ ! -e $CONF/common/etc/$file ]; then
            echo "moving $HOME/.$file to $CONF/common/etc/$file"
            mv $HOME/.$file $CONF/common/etc/$file
        fi
    fi
    echo "making $file link: $HOME/.$file --> $CONF/common/etc/$file"
    ln -s $CONF/common/etc/$file $HOME/.$file
done

# Remove write permissions on a few files
chmod a-w $HOME/.site
chmod a-w $HOME/.conf

# Reload the shell to apply the changes
exec $SHELL
echo "Done with setup, your environment has been initialized"
